DET_SOURCE_DIR: '/aic/code/AIC21-MTMC/datasets/detection/images/train/S01/'
REID_MODEL: 'reid_model/resnet101_ibn_a_3.pth'
REID_BACKBONE: 'resnet101_ibn_a'
DET_IMG_DIR: '/aic/code/AIC21-MTMC/datasets/train/detect_merge/'
DATA_DIR: '/aic/code/AIC21-MTMC/datasets/train/detect_reid3/'
REID_SIZE_TEST: [384, 384]
